# Generated by Django 4.0.4 on 2022-05-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-Createdate',)},
        ),
    ]
