# Generated by Django 4.0.4 on 2022-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contacts_contact_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Createdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
