# Generated by Django 3.2.8 on 2022-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20220516_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
