# Generated by Django 3.2.8 on 2022-05-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contact_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='likes',
        ),
    ]
