# Generated by Django 3.2.8 on 2022-05-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20220516_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='likes_count',
        ),
    ]
